load(":defs.bzl", "constraint_from_configuration")

constraint_from_configuration(
    name = "wasm32",
    configuration = "config//cpu:wasm32",
    visibility = ["PUBLIC"],
)

constraint_setting(
    name = "wasi_version",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "wasip1",
    constraint_setting = ":wasi_version",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "wasip2",
    constraint_setting = ":wasi_version",
    visibility = ["PUBLIC"],
)
