load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "remote_python_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")

load("@wasmono//:defs.bzl", "cxx_wasi_toolchain", "download_wasi_sdk", "wasm_demo_toolchains")

_SYSTEM_AR = select({
    "config//os:windows": None,
    "DEFAULT": "/usr/bin/ar",
})

_SYSTEM_CC = select({
    "config//os:windows": None,
    "DEFAULT": "/usr/bin/clang",
})

_SYSTEM_CXX = select({
    "config//os:windows": None,
    "DEFAULT": "/usr/bin/clang++",
})

system_genrule_toolchain(name = "genrule", visibility = ["PUBLIC"])
system_cxx_toolchain(
    name = "cxx",
    archiver = _SYSTEM_AR,
    compiler = _SYSTEM_CC,
    cxx_compiler = _SYSTEM_CXX,
    linker = _SYSTEM_CXX,
    visibility = ["PUBLIC"],
)
remote_python_toolchain(name = "python", visibility = ["PUBLIC"])
system_rust_toolchain(name = "rust", default_edition = "2024", visibility = ["PUBLIC"])

wasm_demo_toolchains()

download_wasi_sdk(name = "wasi_sdk", version = "33.0")
cxx_wasi_toolchain(name = "cxx_wasi", distribution = ":wasi_sdk", visibility = ["PUBLIC"])
cxx_wasi_toolchain(
    name = "cxx_wasi_p1",
    distribution = ":wasi_sdk",
    target = "wasm32-wasip1",
    visibility = ["PUBLIC"],
)

noop_test_toolchain(name = "test", visibility = ["PUBLIC"])
remote_test_execution_toolchain(name = "remote_test_execution", visibility = ["PUBLIC"])
