export_file(
    name = "test_wrapper",
    src = "test_wrapper.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "asc_build",
    src = "asc_build.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "wit_fetch",
    src = "wit_fetch.py",
    visibility = ["PUBLIC"],
)
