rust_binary(
    name = "validator",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    deps = [
        "//third-party:anyhow",
        "//third-party:wasmtime",
        "//third-party:wasmtime-wasi",
    ],
    env = {
        "COMPONENT_PATH": "$(location //components/validator:validator_with_regex)",
    },
    visibility = ["PUBLIC"],
)
